name: 'Deploy Terraform dev/prod'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment:'
        required: true
        type: choice
        options:
          - PROD
          - DEV
        default: PROD

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Determine AWS Account based on selected environment
    - name: Set AWS Account Variable
      run: |
        if [[ "${{ inputs.environment }}" == "PROD" ]]; then
          echo "AWS_ACCOUNT=957551240854" >> $GITHUB_ENV
        elif [[ "${{ inputs.environment }}" == "DEV" ]]; then
          echo "AWS_ACCOUNT=957551240855" >> $GITHUB_ENV
        fi
      id: set_aws_account

    # Github role in AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/role_github_actions
        aws-region: us-east-1

    # Setup tf cli
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      working-directory: terraform

    # tf init
    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    # tf check
    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    # tf plan
    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: terraform

    # tf apply
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: terraform
