name: 'Deploy Terraform dev/stage/prod'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'environment:'
        required: true
        type: choice
        options:
          - DEV
          - STAGE
          - PROD
        default: DEV

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Determine environment
      run: |
        if [[ "${{ inputs.environment }}" == "DEV" ]]; then
          echo "AWS_ACCOUNT=957551240854" >> $GITHUB_ENV
        elif [[ "${{ inputs.environment }}" == "STAGE" ]]; then
          echo "AWS_ACCOUNT=957551240854" >> $GITHUB_ENV
        elif [[ "${{ inputs.environment }}" == "PROD" ]]; then
          echo "AWS_ACCOUNT=957551240854" >> $GITHUB_ENV
        fi
      id: set_aws_account

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/role_github_actions
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Format
      run: terraform fmt -check
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan -input=false
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: terraform
